
INSERT IGNORE INTO menu
(brand_id, menu_name, img, type)
VALUES 
(3, "아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_aa618eecef95.png", "COFFEE")
,(3, "시그니처 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_e1983f793ad7.png", "COFFEE")
,(3, "클래식 밀크 커피", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d6311728c75e.png", "COFFEE")
,(3, "화이트 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_94adbb1aff86.png", "COFFEE")
,(3, "헥사 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_350a5a914a51.png", "COFFEE")
,(3, "제로슈가 스위트 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_c02fe040d0ad.png", "COFFEE")
,(3, "헤이즐넛 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_dd9bbc721a56.png", "COFFEE")
,(3, "카페 모카", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1418e586eccc.png", "COFFEE")
,(3, "바나리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_7322c5cfdde8.png", "COFFEE")
,(3, "허니 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_b42c5ce307da.png", "COFFEE")
,(3, "카페 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_0a2935abe540.png", "COFFEE")
,(3, "크리미 라뗴", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_85b82596d833.png", "COFFEE")
,(3, "바닐라 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_cd25547832ba.png", "COFFEE")
,(3, "연유 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1c83ee862db7.png", "COFFEE")
,(3, "밀크 카라멜 마끼아또", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6c4dc6cd3999.png", "COFFEE")
,(3, "피스타치오 카페 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a739698cd38a.png", "COFFEE")
,(3, "시나몬 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_0b5cb986f1f7.png", "COFFEE")
,(3, "에스프레소", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/Espresso.png", "COFFEE")
,(3, "콜드브루", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_15fc4e24e77c.png", "COFFEE")
,(3, "시그니처 콜드브루", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_23079ef56016.png", "COFFEE")
,(3, "바닐라 콜드브루", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_5889a996fe45.png", "COFFEE")
,(3, "돌체 콜드브루", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_2cb207acf5d8.png", "COFFEE")
,(3, "콜드브루 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_f3a422f936b2.png", "COFFEE")
,(3, "디카페인 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_496789e1f269.png", "DECAFFEIN")
,(3, "디카페인 화이트 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_86189b417943.png", "DECAFFEIN")
,(3, "디카페인 제로슈거 스위트 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a199cc6f53d3.png", "DECAFFEIN")
,(3, "디카페인 헤이즐넛 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_2b950f0840c4.png", "DECAFFEIN")
,(3, "디카페인 카페 모카", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a97cd1361d31.png", "DECAFFEIN")
,(3, "디카페인 바나리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_81a187b11db2.png", "DECAFFEIN")
,(3, "디카페인 허니 아메리카노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6d19857e14bd.png", "DECAFFEIN")
,(3, "디카페인 카페 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_c4a18dc093ff.png", "DECAFFEIN")
,(3, "디카페인 바닐라 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a88936e8a744.png", "DECAFFEIN")
,(3, "디카페인 크리미 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_14fb5394337e.png", "DECAFFEIN")
,(3, "디카페인 연유 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8348da91cb85.png", "DECAFFEIN")
,(3, "디카페인 피스타치오 카페 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_479e984bf49a.png", "DECAFFEIN")
,(3, "디카페인 에스프레소", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_357aef1d4472.png", "DECAFFEIN")
,(3, "디카페인 시나몬 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_44c34466f721.png", "DECAFFEIN")
,(3, "디카페인 밀크 카라멜 마끼아또", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d5eb7d0cf01c.png", "DECAFFEIN")
,(3, "얼그레이 쇼콜라", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d54385beb484.png", "MILKTEA&LATTE")
,(3, "얼그레이 바닐라 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1d0f987f9cc4.png", "MILKTEA&LATTE")
,(3, "공주 밤 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_64fb32c9f507.png", "MILKTEA&LATTE")
,(3, "공주 밤 루이보스 티 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d57cb162f00e.png", "MILKTEA&LATTE")
,(3, "옥수수 크리미 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_ad5f25ccd7f0.png", "MILKTEA&LATTE")
,(3, "미숫가루 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_68a412ed0616.png", "MILKTEA&LATTE")
,(3, "흑임자 두유 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_08bf9815da74.png", "MILKTEA&LATTE")
,(3, "딸기 크리미 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1a7763176701.png", "MILKTEA&LATTE")
,(3, "얼그레이 밀크티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_0c08e273cd8b.png", "MILKTEA&LATTE")
,(3, "얼그레이 버블티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_148da6d88b38.png", "MILKTEA&LATTE")
,(3, "흑당 밀크티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_57320507b3f8.png", "MILKTEA&LATTE")
,(3, "흑당 버블티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8bdbff00aa9b.png", "MILKTEA&LATTE")
,(3, "토피넛 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_7b8ed53d7eea.png", "MILKTEA&LATTE")
,(3, "달고나 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_ef5e35662c02.png", "MILKTEA&LATTE")
,(3, "리얼 바닐라 빈", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_40bd5666a9ce.png", "MILKTEA&LATTE")
,(3, "리얼 초코", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_3becda51fb3a.png", "MILKTEA&LATTE")
,(3, "오트밀 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_34d763b1820d.png", "MILKTEA&LATTE")
,(3, "녹차 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_ef2fc5c870b5.png", "MILKTEA&LATTE")
,(3, "피스타치오 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_015748897080.png", "MILKTEA&LATTE")
,(3, "딸기 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d505c50ed17e.png", "MILKTEA&LATTE")
,(3, "홍시 라떼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_533c9e27ad61.png", "MILKTEA&LATTE")
,(3, "딸기 쥬스", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6dd7097c7bc4.png", "JUICE")
,(3, "망고 쥬스", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_571b16e834cd.png", "JUICE")
,(3, "홍시 쥬스", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_65a845f42626.png", "JUICE")
,(3, "딸기 요거트 드링크", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_60516dc2a766.png", "JUICE")
,(3, "복숭아 요거트 드링크", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_fdd8ba7e6d64.png", "JUICE")
,(3, "플레인 요거트 드링크", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_2d9281be5946.png", "JUICE")
,(3, "제주 청귤 레몬 스무디", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_968dafd31121.png", "BANACCINO&SMOOTHIE")
,(3, "옥수수 바나 치노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_953dadd8a02a.png", "BANACCINO&SMOOTHIE")
,(3, "딸기 복숭아 스무디", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a07548dac0db.png", "BANACCINO&SMOOTHIE")
,(3, "레몬 요거트 스무디", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_059a6e612b37.png", "BANACCINO&SMOOTHIE")
,(3, "자바칩 바나치노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_dd07c01f41d5.png", "BANACCINO&SMOOTHIE")
,(3, "쿠앤크 바나치노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_e931361e0b59.png", "BANACCINO&SMOOTHIE")
,(3, "녹차 바나치노", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6adea6949d3b.png", "BANACCINO&SMOOTHIE")
,(3, "딸기 스무디", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_ed4fb8081923.png", "BANACCINO&SMOOTHIE")
,(3, "레몬 딸기 스무디", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a500008b4fbb.png", "BANACCINO&SMOOTHIE")
,(3, "망고 스무디", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8fe56ebfe9d2.png", "BANACCINO&SMOOTHIE")
,(3, "바닐라 쉐이크", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_89e794699475.png", "BANACCINO&SMOOTHIE")
,(3, "초코 쉐이크", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_0f4de72e3327.png", "BANACCINO&SMOOTHIE")
,(3, "윈터 레드 뱅쇼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d378f7e3663f.png", "TEA&ADE")
,(3, "홀리데이 로제 뱅쇼", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_754c951f6a9e.png", "TEA&ADE")
,(3, "자몽 허니 블랙티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_015f73efbc1c.png", "TEA&ADE")
,(3, "레몬 허니 블랙티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_4bae65ab0743.png", "TEA&ADE")
,(3, "제주 청귤 에이드", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_00c7cb815f1d.png", "TEA&ADE")
,(3, "문경 오미자 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_fcb3abb8d6e3.png", "TEA&ADE")
,(3, "얼음 동동 식혜", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_fefde224a8e3.png", "TEA&ADE")
,(3, "대추 쌍화차", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d066d06a6593.png", "TEA&ADE")
,(3, "배 도라지 차", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1b01eafee35b.png", "TEA&ADE")
,(3, "캐모마일 리치 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_03b22dd47198.png", "TEA&ADE")
,(3, "복숭아 아이스 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_552d506c2ef9.png", "TEA&ADE")
,(3, "복숭아 에이드", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_c182f1def00d.png", "TEA&ADE")
,(3, "자몽 에이드", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_dae205b2c09a.png", "TEA&ADE")
,(3, "레몬 에이드", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_7f6a0de222cc.png", "TEA&ADE")
,(3, "청포도 에이드", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_221dbe82ebb9.png", "TEA&ADE")
,(3, "제주 청귤 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_5bbe045581aa.png", "TEA&ADE")
,(3, "레몬 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d072b69b03bf.png", "TEA&ADE")
,(3, "자몽 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_fbec2cdf7949.png", "TEA&ADE")
,(3, "자몽 히비스커스 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_3e15ccb10c2a.png", "TEA&ADE")
,(3, "레몬 페퍼민트 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_3e50b115d8cb.png", "TEA&ADE")
,(3, "캐모마일 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8cb806e52dad.png", "TEA&ADE")
,(3, "히비스커스 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_465508a95b24.png", "TEA&ADE")
,(3, "얼그레이 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d0e510a54056.png", "TEA&ADE")
,(3, "페퍼민트 티", "https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8440f3fe6543.png", "TEA&ADE")
;